# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fL7lzHvpGefW11F1IqiqIBGnuVVG2Ak7
"""

from flask import Flask, request
from model import FakeAccClassifier

app = Flask(__name__)

classifier = FakeAccClassifier()

@app.route('/')
def hello():
    return 'Hello World!'

